from common import *
import csv,re,platform,sys,importlib.metadata

def main():
 ref=json.loads((ROOT/'output/reference_audit.json').read_text());support={
 'Dotter2016':'MIST isochrone construction, not binary inference validation','Choi2016':'MIST stellar tracks and solar-scaled models','Riello2021':'Gaia EDR3 photometric content and validation; does not supply the fixed extinction factors','Efron1979':'Bootstrap principle; realization-cluster implementation specified by this paper','Netopil2016':'Homogenized open-cluster metallicity compilation; parameter CSV retains chosen values','Hunt2024':'Cleaned Gaia cluster catalogue used for nuisance/member inputs','Raghavan2010':'Stellar multiplicity motivation only','Gaia2023':'Gaia DR3 survey/data description, not completeness calibration','Chi2025a':'Publisher section 2.3 supports BASE-9/PARSEC and stellar/cluster estimands','Duchene2013':'Stellar multiplicity review and motivation','Li2022':'Primary arXiv abstract explicitly supports 1000 mocks and ten EDR3 clusters','Li2020':'Primary arXiv abstract supports mixture model and NGC3532 DR2 application','Albrow2022':'Method and M67 application as stated in title and abstract','Alexander2025':'Primary arXiv abstract supports generative modelling of six young clusters; two authors','Cordoni2023':'78-cluster photometric binary survey, descriptive context only','Milone2012':'Globular-cluster photometric binaries; manuscript now distinguishes broad cluster surveys','Moe2017':'Binary population distributions and motivation','Lucy1974':'Classical iterative rectification, related mathematics only','Richardson1972':'Classical iterative restoration, related mathematics only','Dempster1977':'General EM framework, not proof of convergence in this benchmark','Brown2001':'Binomial interval estimation, Wilson intervals; discussion-inclusive page range','Albrow2024':'Hyades and Praesepe generative population modelling','Donada2023':'Gaia cluster multiplicity survey, context only','Jadhav2021':'High mass-ratio photometric cluster binary studies, context only','DAgostini2010':'Iterative unfolding, primary arXiv record checked; not basis for posterior label here'}
 lines=['# REFERENCE AUDIT','', 'All 25 baseline entries checked against DOI metadata (24 Crossref records cached) or primary arXiv record. Retained valid years and bibliographic fields. The 2025 Alexander volume is retained despite online publication in 2024. Alexander has two authors: removed erroneous "and others". Li 2020 full author list restored. Chi page range standardized. No newer citation substituted for a valid source.','', '|Key|Primary source|Metadata/statement check|','|---|---|---|']
 for r in ref:
  key=r['key'];url=r.get('url','https://doi.org/'+r.get('doi',''));lines.append(f'|{key}|[{r.get("doi", "arXiv record")}]({url})|{support[key]}|')
 lines+=['','Crossref omits complete page ranges for Brown/Efron and stores starting pages for Lucy/Richardson; complete original page ranges retained (Brown 101–133 including discussion; Efron 1–26; Lucy 745–754; Richardson 55–59). Publisher/primary bibliographic records were inspected rather than interpreting absent metadata as disagreement.','', 'Claim-context primary records: [MiMO](https://arxiv.org/abs/2112.08028), [Li 2020](https://arxiv.org/abs/2008.04684), [Alexander](https://arxiv.org/abs/2411.16089), [Chi section 2.3](https://academic.oup.com/pasj/article/77/5/1050/8236289), [D Agostini](https://arxiv.org/abs/1010.0632). No citation is asserted to validate the benchmark response or its intervals.']
 (ROOT/'reports/REFERENCE_AUDIT.md').write_text('\n'.join(lines)+'\n')
 u,joint,fixed=truths();cal=np.load(L/'calibration_200k.npz',allow_pickle=True);assert np.array_equal(cal['m1_edges'],[1,1.5,2,2.5,3,4,5]);assert np.allclose(cal['q_edges'],np.arange(.1,1.01,.1));assert np.allclose(Q,np.tile((cal['q_edges'][:-1]+cal['q_edges'][1:])/2,6))
 eps=R[:,:-1].sum(1);eta=u@eps;selected=u*eps/eta;A=R[:,:-1]/eps[:,None];assert np.max(abs(selected@A-project(u)))<1e-14
 math={'states':6*9,'response_shape':list(R.shape),'row_sum_max_residual':float(max(abs(R.sum(1)-1))),'efficiency_range':[float(min(eps)),float(max(eps))],'selected_projection_residual':float(max(abs(selected@A-project(u)))),'truth_normalization_residuals':{k:float(abs(t.sum()-1)) for k,t in [('null',u),('joint',joint),('fixed_m1',fixed)]},'fixed_M1_residual':float(max(abs(fixed.reshape(6,9).sum(1)-u.reshape(6,9).sum(1)))),'q_centers':Q.tolist(),'flattening':'M1-major then q-minor for states; inverse grid argmin q-major is separate','EM':'algebraic update pi*(R @ [counts/(pi @ R)]) / epsilon, normalized; agrees with explicit responsibility update','zero_efficiency':'not present; guard cannot identify unobserved states','interval_percentiles':[.16,.84],'structural_zero_prior':'empirical support sensitivity; does not prove physical zeros'}
 savejson(ROOT/'output/mathematical_audit.json',math);(ROOT/'reports/MATHEMATICAL_AUDIT.md').write_text('# MATHEMATICAL AUDIT\n\nPASS. Equation definitions match checked arrays and implementation. Unit efficiency makes archived full-state and observed-state probability projection consistent. No zero-efficiency state occurs. Hard-grid inverse ordering differs from final state flattening and is explicitly described.\n\n```json\n'+json.dumps(math,indent=2)+'\n```\n')
 env={k:importlib.metadata.version(k) for k in ['numpy','scipy','matplotlib','numba','pytest']};env['python']=sys.version;env['platform']=platform.platform();savejson(ROOT/'provenance/environment.json',env)
 (ROOT/'environment.yml').write_text('name: pasp-final\nchannels: [conda-forge]\ndependencies:\n  - python='+str(sys.version_info.major)+'.'+str(sys.version_info.minor)+'\n'+''.join('  - '+k+'='+v+'\n' for k,v in env.items() if k not in ['python','platform'])+'  - pip\n')
 claims=[('Three operating characteristics require separate validation','C','Inference framework; mathematically different target quantities'),('Historical detection powers 0.1025/0.6815','A','baseline.json; power NPZ focus cell'),('Fixed-M1 common-target powers 0.0857/0.5030','B','size_matched_tests/results.json'),('Historical S0/S1 estimator errors exceed fixed uniform','A','archived errors and exact truth comparison'),('New fits have substantial cap sensitivity','B','convergence/per_fit_diagnostics.csv; not historical traces'),('Nonuniform truths extend benchmark; limited improvement at 200 steps','B','reconstruction_extended/summary.json and all counts'),('Historical intervals cover 84.0–85.8 percent','A','coverage per-realization counts'),('Zero-preserving new intervals cover 87.9–90.0 percent','B','response_prior endpoints and counts'),('Overcoverage persists without zero-cell filling','C','Independent structural-zero experiment; cannot attribute unpaired differences to prior alone'),('Sensitivity does not establish local reconstruction or calibrated uncertainty','C','Distinct estimands and contrasts within this response'),('Conditional scope and true nuisance values supplied','D','forward/inverse implementation; no empirical astrophysics claim')]
 with (ROOT/'reports/claim_evidence.csv').open('w') as f:w=csv.writer(f);w.writerow(['claim','class','evidence']);w.writerows(claims)
 (ROOT/'reports/CLAIM_AUDIT.md').write_text('# CLAIM AUDIT\n\nA archived support; B new support; C bounded interpretation; D limitation; E unsupported. No E retained.\n\n|Abstract/conclusion claim|Class|Evidence|\n|---|---|---|\n'+'\n'.join('|'+ '|'.join(r)+'|' for r in claims)+'\n\nTitle retained: fixed-M1 experiment completed and retains specified-q sensitivity. Conclusions contain no new numerical result or universal ranking. No Gaia completeness, simultaneous nuisance inference, arbitrary distribution recovery, posterior calibration, or physical mass dependence is claimed.\n')
 (ROOT/'reports/TERMINOLOGY_AUDIT.md').write_text('# TERMINOLOGY AUDIT\n\nStatistical detection: rejection of a specified distributional departure, distinguished at first use from observational retention. Calibration: frozen simulated response or repeated-sampling interval evaluation, not Gaia completeness. Posterior: only prior literature or explicitly negated procedural claim. Recovery: latent reconstruction, not rejection. Bias: replaced by signed mean error except generic literature context. Power: specified-alternative rejection fraction at stated threshold. Coverage: nominal marginal intervals, empirically measured with realization-cluster uncertainty; all-54 containment separately defined. Internal IDs absent from reader-facing text/figures.\n')
 (ROOT/'reports/CATALOGUE_EXTINCTION_AUDIT.md').write_text('# CATALOGUE AND EXTINCTION AUDIT\n\nSix clusters read directly from arch_code_results/data/hunt24/params.csv; exact centers exported in generated table. Generator source selects nominal-support subsets; NGC188/NGC6791 never enter those subsets. This is distinct from whether a randomly perturbed old-cluster isochrone could ever support a component.\n\nExtinction factors traced to line 43 of both archived forward_model.py copies: (0.789,1.083,0.634). No derivation, citation, or R_V assumption found in retained source. The final manuscript transparently labels these fixed implementation choices, supplies no fabricated citation, and does not assign R_V=3.1 by analogy with prior literature.\n\nOptional tie-breaking, matched-grid and no-noise ablations NOT RUN: raw forward inputs exist locally, but these are new response-building tasks outside the prioritized frozen-response revision. No assertion of negligible ties or causally isolated grid effects is made.\n')
 (ROOT/'reports/CHANGELOG_SCIENTIFIC.md').write_text('''# SCIENTIFIC CHANGELOG

## A. NEW ANALYSIS
Fixed-M1 truth and detection (20,000 alternatives); common-target-size thresholds (200,000 nulls), independent sizes (100,000), powers (20,000/design); independent convergence and empirical-zero response perturbations (40,040 fits at four caps); three nonuniform truths (500 realizations each). All seeds, draws, counts, endpoints and vectors stored separately.

## B. REANALYSIS OF FROZEN OUTPUTS
Baseline quantities verified from NPZ/JSON/CSV. Integer calibration counts resolved exactly within floating precision. Archived historical fit authentication BLOCKED by missing counts/vectors; no synthetic historical traces generated. Historical interval widths retrieved from stored summary, not inferred.

## C. TEXTUAL CLARIFICATION
Detection versus photometric selection; joint-cell versus fixed-M1 estimand; finite-iteration estimator versus converged ML; marginal coverage versus all-state containment; empirical zero support versus structural truth; true nuisance values; six catalogue entries; fixed extinction choices. Abstract rewritten after results; discussion limited to four conceptual subsections.

## D. FIGURE/TABLE MODIFICATION
Five original scientific figures regenerated from machine-readable inputs; neutral missing-category separator; clear uniform baseline; descriptive projection names. Compact nonuniform extension figure in appendix. Four generated tables: historical reconstruction, common-target detection, interval procedure summary, catalogue centers.

## E. REPRODUCIBILITY/PROVENANCE
Original hashes, inventories, environment, deterministic scripts, stored new outputs, mathematical and claim audits, reference metadata and changes, source/text diff. Real public repository verified; no existing tagged releases found. Revision release/commit/date/DOI remain explicit deposit placeholders.

## F. NO-CHANGE ITEMS
Frozen response and historical source/result files untouched. Authors and original title retained. No new algorithm, population discovery, Gaia completeness, universal test ranking, globally calibrated intervals, or arbitrary-cluster transfer claim.
''')
 print('audits written')
if __name__=='__main__':main()
